### ISSUE TITLE
Sample State

### ISSUE THREAD

**Issue by PLUCS2** [philowe94/levernote#3]
- [x] You need a sessions slice of state 
- [x] Unless you are sharing notes you will only ever have one user in your state at any given time 
- [x] How do you know which notes are associated with which tag? 
- [x] You will need information about when a note was created so you can display something like "created a day ago" or "edited last week" 
- [x] Do you have any modals or loading pages in the application?

Let me know if you have any questions!

**Comment by philowe94** [comment]
Completed all of the necessary changes
