### ISSUE TITLE
Routes

### ISSUE THREAD

**Issue by PLUCS2** [philowe94/levernote#4]
## Backend 
- [x] These routes seem redundant - is there a way to look at a single notebook without looking at all of its notes? 
- GET /api/notebooks/:notebookId gets a specific current user's notebook
- GET /api/notebooks/:notebookId/notes gets all the notes inside the notebook
- [x] `adds a notebook to the current users notebooks` what does this mean? 
- [x] `adds a tag to the current users tag` what does this mean?  
- [x] What is the specific information returned from a specific tag? (Is it all the notes with that tag?) 

## Frontend 
- [x] It looks to my like signup is a page rather than a modal - where did you see it as a modal? 
- [x] What is the distinction between "signup" and "register" 
- [x] Specify if there are sidebar components, headers, or footers 

Nice work! Let me know if you have any questions

**Comment by philowe94** [comment]
Completed all of the necessary changes
